version: '3.9'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=senso
      - MARIADB_ROOT_PASSWORD=toor
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8082:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    restart: unless-stopped

  php-fpm:
    container_name: php-fpm
    image: senso-app
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile.dev
    volumes:
      - ./:/var/www/html:cached
    networks:
      - default
      - senso-shared
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.19.7-alpine
    ports:
      - 8000:80
    depends_on:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www/html:cached
    restart: unless-stopped

volumes:
  db-data:

networks:
  senso-shared:
    external: true