<?php

namespace AppBundle\Repository;

/**
 * CitizenshipDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitizenshipDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
