<?php

namespace App\Repository;

use App\Entity\Address;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;


/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {


        parent::__construct($registry, Address::class);
    }

    public function checkAddressDuplicates($street, $postcode, $city)
    {

    }
}
