<?php

namespace App\Repository;

/**
 * BankDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
