<?php

namespace App\Repository;

use App\Entity\ClientContract;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\DBAL\DBALException;
use Symfony\Bridge\Doctrine\RegistryInterface;


/**
 * ClientContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientContractRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ClientContract::class);
    }


    /**
     * @param $userid
     */
    public function listPerUserAndClient($userid)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                            
                            select c, cc
                            from App\Entity\ClientContract c
                            join App\Entity\ContactEndClient cc
                            where c.user = :user
                      ');

        $query->setParameter('user', $userid);

        $query->getResult();
    }

    /**
     * @param $firstname
     * @param $lastname
     * @return mixed
     * @throws DBALException
     */
    public function getListPerUser($firstname, $lastname)
    {
            $em = $this->getEntityManager();

            $query = '
            SELECT clientname 
            FROM contact_end_client c
            INNER JOIN client_contract cli ON cli.clientname_id = c.id 
            INNER JOIN user u ON u.id = cli.user_id
            WHERE u.firstname = :firstname AND u.lastname = :lastname
            ';

            $stmt = $em->getConnection()->prepare($query);
            $param = ['firstname'=> $firstname, 'lastname' => $lastname];
            $stmt->execute($param);
            return $stmt->fetchAll();
    }
}
