<?php

namespace App\Repository;

use App\Entity\ClientContract;
use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\DBAL\DBALException;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;


/**
 * ClientContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientContractRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ClientContract::class);
    }


    /**
     * @param $userid
     */
    public function listPerUserAndClient($userid)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                            
                            select c, cc
                            from App\Entity\ClientContract c
                            join App\Entity\ContactEndClient cc
                            where c.user = :user
                      ');

        $query->setParameter('user', $userid);

        $query->getResult();
    }

    /**
     * @param $id
     * @return mixed
     * @throws DBALException
     */
    public function getListPerUser($id)
    {
        $em = $this->getEntityManager();

        $query = '
            SELECT cli.id, clientname, cli.user_id 
            FROM contact_end_client c
            INNER JOIN client_contract cli ON cli.clientname_id = c.id AND  cli.active
            INNER JOIN user u ON u.id = cli.user_id
            WHERE u.id = :id AND cli.active = 1
            ';

        $stmt = $em->getConnection()->prepare($query);
        $param = ['id' => $id];
        $stmt->execute($param);
        return $stmt->fetchAll();
    }
}