<?php

namespace App\Repository;

/**
 * ClientContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientContractRepository extends \Doctrine\ORM\EntityRepository
{
}
