<?php

namespace App\Repository;

/**
 * PayrollPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayrollPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
